# Generated by Django 4.0.3 on 2022-04-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Getintouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='your name', max_length=50)),
                ('email', models.CharField(default='_@_', max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('subject', models.TextField(max_length=255)),
            ],
        ),
    ]
