# Generated by Django 4.0.3 on 2022-03-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'On'), ('deactive', 'Off')], max_length=30)),
                ('content', models.TextField(default='UNKNOWN')),
                ('image', models.ImageField(upload_to='blogs')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
