# Generated by Django 4.0.3 on 2022-04-11 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default='Unknown', max_length=50, null=True)),
                ('age', models.IntegerField(default=18)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'On'), ('deactive', 'Off')], max_length=30)),
                ('content', models.TextField(default='UNKNOWN', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.author')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ('-price',),
            },
            managers=[
                ('bloglar', django.db.models.manager.Manager()),
            ],
        ),
    ]
