# Generated by Django 4.0.3 on 2022-03-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
