# Generated by Django 4.0.3 on 2022-03-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fullname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.author'),
        ),
    ]
