# Generated by Django 4.0.3 on 2022-03-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='Fullname',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='fullname',
            new_name='author',
        ),
    ]
