# Generated by Django 4.0.3 on 2022-03-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_name_author_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Fullname',
            new_name='fullname',
        ),
    ]
