# Generated by Django 4.0.3 on 2022-03-28 18:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_fullname_author_fullname'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('bloglar', django.db.models.manager.Manager()),
            ],
        ),
    ]
