# Generated by Django 4.0.3 on 2022-03-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-published',), 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
