# Generated by Django 4.0.3 on 2022-03-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-price',), 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
