# Generated by Django 4.0.3 on 2022-03-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fligth_status', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('plane_name', models.CharField(blank=True, max_length=40, null=True)),
                ('aircondition', models.CharField(default='Unknown', max_length=30)),
                ('about', models.TextField(blank=True, max_length=40, null=True)),
                ('fl_score', models.IntegerField(default=0)),
                ('model_year', models.IntegerField(default=4)),
                ('rent_price', models.IntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='planePics/')),
            ],
        ),
    ]
