# Generated by Django 4.0.3 on 2022-03-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='company',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='fligth_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
