# Generated by Django 4.0.3 on 2022-03-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, default='Unknown', null=True)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='aircondition',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='company',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='fligth_status',
            field=models.CharField(blank=True, choices=[('Onair', 'onair'), ('Onland', 'onland')], default='UNKNOWN', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='model_year',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='airliner',
            field=models.ManyToManyField(to='aircrafts.airliner'),
        ),
    ]
