# Generated by Django 4.0.3 on 2022-03-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0002_alter_aircraft_about_alter_aircraft_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='fligth_status',
            field=models.CharField(blank=True, choices=[('Onair', 'onair'), ('Onland', 'onland')], max_length=40, null=True),
        ),
    ]
