# Generated by Django 4.0.3 on 2022-03-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0003_alter_aircraft_fligth_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='aircondition',
        ),
    ]
