# Generated by Django 4.0.3 on 2022-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0005_alter_aircraft_fligth_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, default='Unknown', null=True)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='company',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='airliner',
            field=models.ManyToManyField(to='aircrafts.airliner'),
        ),
    ]
