# Generated by Django 4.0.3 on 2022-03-29 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0006_airliner_remove_aircraft_company_aircraft_airliner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='model_year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
