# Generated by Django 4.0.3 on 2022-03-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0007_alter_aircraft_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='model_year',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
