# Generated by Django 4.0.3 on 2022-03-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shareit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('fullname', models.CharField(default='Unknown', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='shares/')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=70)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
