# Generated by Django 4.0.3 on 2022-03-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareit',
            old_name='likes',
            new_name='price',
        ),
    ]
