# Generated by Django 4.0.3 on 2022-03-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_company_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
    ]
