# Generated by Django 4.0.3 on 2022-03-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
