# Generated by Django 4.0.3 on 2022-04-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown', max_length=150)),
                ('city_address', models.CharField(default='Unknown', help_text='detailed address', max_length=150)),
            ],
            options={
                'verbose_name': 'Textile Company',
                'verbose_name_plural': 'Textile Companies',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Cl_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('about', models.TextField(default='Nothing')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tax_Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='place', max_length=200)),
                ('TIN', models.CharField(error_messages={'unique': 'this number already exists'}, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='unknown', max_length=50)),
                ('genders', models.CharField(help_text='Men,Women,Unisex', max_length=10)),
                ('info', models.TextField(blank=True, max_length=80, null=True)),
                ('size', models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Xlarge', 'XL'), ('XXLarge', 'XXL'), ('XXXLarger', 'XXXL')], max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('cl_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='clothes.cl_type')),
                ('company', models.ManyToManyField(to='clothes.cl_company')),
                ('stores', models.ManyToManyField(to='clothes.store')),
            ],
            options={
                'verbose_name': 'Cloth',
                'verbose_name_plural': 'Clothes',
                'ordering': ('-size',),
            },
        ),
        migrations.AddField(
            model_name='cl_company',
            name='TIN',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.tax_office'),
        ),
    ]
