# Generated by Django 4.0.3 on 2022-03-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_company',
            name='TIN',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.tax_office'),
        ),
    ]
