# Generated by Django 4.0.3 on 2022-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='genders',
            field=models.CharField(default=(('Men', 'M'), ('Women', 'W'), ('Unisex', 'Uni')), max_length=10),
        ),
    ]
