# Generated by Django 4.0.3 on 2022-03-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_cloth_genders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='genders',
            field=models.CharField(default='M,W,UNS', max_length=10),
        ),
    ]
