# Generated by Django 4.0.3 on 2022-03-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_cl_company_tin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='cloth',
            name='stores',
            field=models.ManyToManyField(to='clothes.store'),
        ),
    ]
