# Generated by Django 4.0.3 on 2022-03-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_store_cloth_stores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cl_company',
            old_name='city',
            new_name='city_address',
        ),
    ]
