# Generated by Django 4.0.3 on 2022-03-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_cloth_genders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
