# Generated by Django 4.0.3 on 2022-03-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_rename_city_cl_company_city_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cl_company',
            options={'ordering': ('-name',), 'verbose_name': 'Textile Company', 'verbose_name_plural': 'Textile Companies'},
        ),
    ]
