# Generated by Django 4.0.3 on 2022-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_rename_number_tax_office_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='genders',
            field=models.CharField(default='Men,Women,Unisex', max_length=10),
        ),
    ]
