# Generated by Django 4.0.3 on 2022-04-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_alter_cloth_genders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_company',
            name='city_address',
            field=models.CharField(default='Unknown', help_text='detailed address', max_length=150),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='genders',
            field=models.CharField(help_text='Men,Women,Unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='tax_office',
            name='TIN',
            field=models.CharField(error_messages={'unique': 'this number already exists'}, max_length=10, unique=True),
        ),
    ]
