# Generated by Django 4.0.3 on 2022-04-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='your name', max_length=50)),
                ('lastname', models.CharField(help_text='your surname', max_length=50)),
                ('email', models.CharField(default='_@_', max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('subject', models.TextField(max_length=255)),
            ],
        ),
    ]
