# Generated by Django 4.0.3 on 2022-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
